title: Jetzt bewerben
body: Jetzt Bewerben! Dafür genügt ein Link zu deinem Portfolio, ein paar Sätze zu deiner Person und Angaben zu deinen Gehaltsvorstellungen.
recipient:
  name: Marc
  title: Managing Director
  image: images/team/marc
